apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
spec:
  type: NodePort
  selector:
    run: guacamole 
  ports:
    - protocol: TCP
      port: 8080       
      targetPort: 8080 
      nodePort: 30088 # you can change it
